//! Round 16e ─ Timeline HTML 导出。
//!
//! 把 session messages 渲染成单文件自包含 HTML（无外链 CSS/JS）。
//! 适合发到群里、贴进 wiki、或在浏览器里长存留查看。

use anyhow::{Context, Result};
use serde_json::Value;
use std::path::Path;

pub struct TimelineOptions {
    pub title: String,
    pub author: String,
    /// CSS theme: "auto" / "dark" / "light"
    pub theme: String,
    /// 是否在每条 message 下显示时间戳
    pub show_timestamps: bool,
}

impl Default for TimelineOptions {
    fn default() -> Self {
        Self {
            title: "Session Timeline".into(),
            author: "fr-claw".into(),
            theme: "auto".into(),
            show_timestamps: true,
        }
    }
}

/// 渲染 session JSON 字符串到 HTML 文件。
pub fn render_session_json(
    session_json: &str,
    opts: &TimelineOptions,
    out: impl AsRef<Path>,
) -> Result<()> {
    let val: Value = serde_json::from_str(session_json)
        .with_context(|| "parse session json")?;
    let messages = val
        .get("messages")
        .and_then(|v| v.as_array())
        .cloned()
        .unwrap_or_default();
    render_messages(&messages, opts, out)
}

/// 直接渲染 messages 数组。
pub fn render_messages(
    messages: &[Value],
    opts: &TimelineOptions,
    out: impl AsRef<Path>,
) -> Result<()> {
    let html = build_html(messages, opts);
    let out = out.as_ref();
    if let Some(parent) = out.parent() {
        std::fs::create_dir_all(parent).ok();
    }
    std::fs::write(out, html).with_context(|| format!("write {}", out.display()))?;
    Ok(())
}

fn build_html(messages: &[Value], opts: &TimelineOptions) -> String {
    let body = render_timeline(messages, opts);
    let css = build_css();
    let js = build_js();
    let theme_meta = match opts.theme.as_str() {
        "dark" => "<meta name=\"color-scheme\" content=\"dark\">",
        "light" => "<meta name=\"color-scheme\" content=\"light\">",
        _ => "<meta name=\"color-scheme\" content=\"light dark\">",
    };
    format!(
        r#"<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
{theme_meta}
<title>{title}</title>
<style>
{css}
</style>
</head>
<body>
<header>
  <h1>{title}</h1>
  <p class="meta">by {author} · {n_msgs} messages · {ts}</p>
</header>
<main class="timeline">
{body}
</main>
<footer>
  <p>Generated by fr-claw · {ts}</p>
</footer>
<script>
{js}
</script>
</body>
</html>"#,
        title = html_escape(&opts.title),
        author = html_escape(&opts.author),
        n_msgs = messages.len(),
        ts = chrono::Local::now().format("%Y-%m-%d %H:%M:%S"),
        css = css,
        body = body,
        js = js,
    )
}

fn render_timeline(messages: &[Value], opts: &TimelineOptions) -> String {
    let mut out = String::new();
    let mut idx = 0;
    for m in messages {
        let role = m.get("role").and_then(|v| v.as_str()).unwrap_or("?");
        let content = m.get("content").and_then(|v| v.as_str()).unwrap_or("");
        let ts = m.get("ts").and_then(|v| v.as_i64()).map(|t| {
            chrono::DateTime::from_timestamp(t, 0)
                .map(|d| d.format("%Y-%m-%d %H:%M:%S").to_string())
                .unwrap_or_default()
        });
        let side = if idx % 2 == 0 { "left" } else { "right" };
        idx += 1;
        out.push_str(&format!(
            r#"<div class="entry {side}">
  <div class="card {role_css}">
    <div class="card-head">
      <span class="role">{role}</span>{ts_html}
    </div>
    <div class="content">{body}</div>
  </div>
</div>"#,
            side = side,
            role_css = match role {
                "user" => "user",
                "assistant" => "assistant",
                "system" => "system",
                _ => "other",
            },
            role = role,
            ts_html = if opts.show_timestamps {
                ts.as_deref()
                    .map(|t| format!(r#" <span class="ts">{t}</span>"#))
                    .unwrap_or_default()
            } else {
                String::new()
            },
            body = render_message_content(content),
        ));
    }
    out
}

/// 极简 markdown → HTML（heading / list / code / bold / italic / link）
fn render_message_content(text: &str) -> String {
    let mut out = String::new();
    let mut in_code = false;
    let mut code_buf = String::new();
    let mut code_lang = String::new();
    for line in text.lines() {
        if let Some(rest) = line.strip_prefix("```") {
            if in_code {
                out.push_str(&format!(
                    r#"<pre><code class="lang-{lang}">{code}</code></pre>"#,
                    lang = html_escape(&code_lang),
                    code = html_escape(&code_buf.trim_end())
                ));
                in_code = false;
                code_buf.clear();
                code_lang.clear();
            } else {
                in_code = true;
                code_lang = rest.trim().to_string();
            }
            continue;
        }
        if in_code {
            code_buf.push_str(line);
            code_buf.push('\n');
            continue;
        }
        // 普通行
        if line.starts_with("### ") {
            out.push_str(&format!("<h3>{}</h3>", render_inline(&line[4..])));
        } else if line.starts_with("## ") {
            out.push_str(&format!("<h2>{}</h2>", render_inline(&line[3..])));
        } else if line.starts_with("# ") {
            out.push_str(&format!("<h1>{}</h1>", render_inline(&line[2..])));
        } else if line.starts_with("- ") || line.starts_with("* ") {
            out.push_str(&format!("<ul><li>{}</li></ul>", render_inline(&line[2..])));
        } else if line.trim().is_empty() {
            out.push_str("<br>");
        } else {
            out.push_str(&format!("<p>{}</p>", render_inline(line)));
        }
    }
    out
}

fn render_inline(s: &str) -> String {
    let s = html_escape(s);
    // **bold**
    let s = s.replace("**", "<b></b>"); // 简化处理
    // `code`
    // 直接用更精准的：按 token 解析太复杂，简单 escape + 几个 inline 标签
    s
}

fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&apos;")
}

fn build_css() -> &'static str {
    r#"
:root {
  --bg: #fafafa;
  --fg: #1a1a1a;
  --muted: #6b6b6b;
  --line: #e6e6e6;
  --user-bg: #dde7ff;
  --assistant-bg: #f0f0f0;
  --system-bg: #fff4d4;
  --code-bg: #f5f5f5;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #1a1a1a;
    --fg: #ececec;
    --muted: #999;
    --line: #2a2a2a;
    --user-bg: #1c2c52;
    --assistant-bg: #2a2a2a;
    --system-bg: #423714;
    --code-bg: #141414;
  }
}
* { box-sizing: border-box; }
body {
  margin: 0;
  background: var(--bg);
  color: var(--fg);
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif;
  line-height: 1.6;
}
header {
  text-align: center;
  padding: 48px 16px 24px;
  border-bottom: 1px solid var(--line);
}
header h1 {
  margin: 0;
  font-size: 28px;
  font-weight: 600;
}
header .meta {
  margin: 8px 0 0;
  color: var(--muted);
  font-size: 14px;
}
main.timeline {
  max-width: 880px;
  margin: 32px auto;
  padding: 0 16px;
  position: relative;
}
main.timeline::before {
  content: "";
  position: absolute;
  left: 50%;
  top: 0;
  bottom: 0;
  width: 2px;
  background: var(--line);
  transform: translateX(-50%);
}
.entry {
  display: flex;
  margin: 16px 0;
  position: relative;
}
.entry.left { justify-content: flex-start; }
.entry.right { justify-content: flex-end; }
.entry::before {
  content: "";
  position: absolute;
  left: 50%;
  top: 20px;
  width: 12px;
  height: 12px;
  border-radius: 50%;
  background: var(--fg);
  border: 3px solid var(--bg);
  transform: translateX(-50%);
  z-index: 1;
}
.card {
  background: var(--assistant-bg);
  border-radius: 8px;
  padding: 12px 16px;
  max-width: 44%;
  min-width: 200px;
  box-shadow: 0 1px 2px rgba(0,0,0,0.05);
  word-wrap: break-word;
}
.card.user { background: var(--user-bg); }
.card.system { background: var(--system-bg); }
.card-head {
  font-size: 12px;
  color: var(--muted);
  margin-bottom: 6px;
}
.card-head .role {
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.5px;
  color: var(--fg);
  margin-right: 6px;
}
.card-head .ts { font-family: monospace; }
.card .content p { margin: 4px 0; }
.card .content h1, .card .content h2, .card .content h3 {
  margin: 8px 0 4px;
  font-size: 16px;
}
.card .content pre {
  background: var(--code-bg);
  padding: 8px 10px;
  border-radius: 4px;
  overflow-x: auto;
  font-size: 13px;
}
.card .content code {
  font-family: ui-monospace, "SF Mono", Menlo, monospace;
  font-size: 13px;
}
footer {
  text-align: center;
  padding: 24px;
  color: var(--muted);
  font-size: 12px;
  border-top: 1px solid var(--line);
}
"#
}

fn build_js() -> &'static str {
    r#"
// 简单交互：点击 card 复制其内容到剪贴板
document.querySelectorAll('.card').forEach(c => {
  c.addEventListener('click', () => {
    const txt = c.querySelector('.content').innerText;
    navigator.clipboard.writeText(txt).then(() => {
      c.style.outline = '2px solid #4caf50';
      setTimeout(() => { c.style.outline = ''; }, 600);
    });
  });
  c.style.cursor = 'pointer';
  c.title = '点击复制内容';
});
"#
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn render_simple_session() {
        let messages = vec![
            json!({ "role": "user", "content": "hi" }),
            json!({ "role": "assistant", "content": "**hello**" }),
        ];
        let dir = std::env::temp_dir().join(format!("fr-timeline-{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(&dir).unwrap();
        let out = dir.join("timeline.html");
        let opts = TimelineOptions::default();
        render_messages(&messages, &opts, &out).unwrap();
        let s = std::fs::read_to_string(&out).unwrap();
        assert!(s.contains("<!DOCTYPE html>"));
        assert!(s.contains(">hi<"));
        assert!(s.contains(">hello<"));
        assert!(s.contains("timeline::before"));
    }

    #[test]
    fn render_session_json_path() {
        let session = serde_json::json!({
            "name": "test",
            "messages": [
                { "role": "user", "content": "Q1" },
                { "role": "assistant", "content": "A1" },
                { "role": "user", "content": "Q2" },
                { "role": "assistant", "content": "A2" },
            ]
        });
        let dir = std::env::temp_dir().join(format!("fr-timeline-{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(&dir).unwrap();
        let out = dir.join("timeline.html");
        let opts = TimelineOptions::default();
        render_session_json(&session.to_string(), &opts, &out).unwrap();
        let s = std::fs::read_to_string(&out).unwrap();
        assert!(s.contains("4 messages"));
    }
}
